import '../global.css';

export const metadata = {
    title: "Students",
    description: "Generated by create next app",
};

const Students = () =>{
    return (
        
        <div>
            <h2>Student Information Page</h2>
        </div>
    );
}
export default Students;