import '../global.css';

export const metadata = {
    title: "About us",
    description: "Generated by create next app",
  };

const About = () =>{
    return (
        <div>
            <h2>About</h2>
        </div>
    );
}
export default About;